### ISSUE TITLE
not compatible with latest neoforge api (1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [stal111/Clean-Tooltips#32]
https://mclo.gs/nB99mxf

**Comment by ffuentesm** [comment]
Getting same crash on Neoforge 21.1.61

[client-1.21.1-20240808.144430-srg.jar%23336!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?] {}
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method cleanTooltips_getTooltipLines$addDurabilityTooltip(Ljava/util/function/Consumer;)Ljava/util/function/Consumer; in clean_tooltips-common.mixins.json:ItemStackMixin from mod clean_tooltips failed injection check, (0/1) succeeded. Scanned 0 target(s). No refMap loaded.

**Comment by SkyRunner55** [comment]
i tested out and yes this mod don't work and on the latest neoforge version

**Comment by VaporeonScripts** [comment]
the mod has updated,probably fixed this issue, the issue is now closed,if i find any issues i will report them there!
